version: "3.9"
services:
  production_info_bot:
    build: .
    restart: unless-stopped
    image: production_info_bot
    container_name: production_info_bot_co
# networks:
#   default:
#     external: true
#     name: autohunt_network
